# -*- mode: ruby -*-
# vi: set ft=ruby :

# Multi-Machine Environment mimicking production environment using Vagrant
Vagrant.configure("2") do |config|

    config.vm.define "jenkins_ansible_master" do |ansjenkins|
        ansjenkins.vm.box = "debian/buster64"
        ansjenkins.vm.hostname = "ansjenkins"
        config.vm.network "private_network", ip: "192.168.10.10"
        
        config.vm.provider "virtualbox" do |vb|
            vb.linked_clone = true
            vb.memory = 1024
            vb.cpus = 2
        end
    end    

    config.vm.define "loadbalancer" do |loadbalancer|
        loadbalancer.vm.box = "debian/buster64"
        loadbalancer.vm.hostname = "loadbalancer"
        config.vm.network "private_network", ip: "192.168.10.11"

        config.vm.provider "virtualbox" do |vb|
            vb.linked_clone = true
            vb.memory = 1024
            vb.cpus = 2
        end
    end    

    config.vm.define "webserver" do |webserver|
        webserver.vm.box = "debian/buster64"
        webserver.vm.hostname = "webserver"
        config.vm.network "private_network", ip: "192.168.10.12"

        config.vm.provider "virtualbox" do |vb|
            vb.linked_clone = true
            vb.memory = 1024
            vb.cpus = 2
        end
    end    

    config.vm.define "apigateway" do |apigateway|
        apigateway.vm.box = "debian/buster64"
        apigateway.vm.hostname = "apigateway"
        config.vm.network "private_network", ip: "192.168.10.13"

        config.vm.provider "virtualbox" do |vb|
            vb.linked_clone = true
            vb.memory = 1024
            vb.cpus = 2
        end
    end    

    config.vm.define "clinic" do |clinic|
        clinic.vm.box = "debian/buster64"
        clinic.vm.hostname = "clinic"
        config.vm.network "private_network", ip: "192.168.10.14"

        config.vm.provider "virtualbox" do |vb|
            vb.linked_clone = true
            vb.memory = 1024
            vb.cpus = 2
        end
    end    

    config.vm.define "doctor" do |doctor|
        doctor.vm.box = "debian/buster64"
        doctor.vm.hostname = "doctor"
        config.vm.network "private_network", ip: "192.168.10.15"

        config.vm.provider "virtualbox" do |vb|
            vb.linked_clone = true
            vb.memory = 1024
            vb.cpus = 2
        end
    end    

    config.vm.define "riak" do |db|
        db.vm.box = "debian/buster64"
        db.vm.hostname = "riak"
        config.vm.network "private_network", ip: "192.168.10.16"

        config.vm.provider "virtualbox" do |vb|
            vb.linked_clone = true
            vb.memory = 1024
            vb.cpus = 2
        end
    end    

    
    config.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y tree
    SHELL
  
  end
  