---
# Installation of PostgreSQL and setup for Sonarqube
# PostgreSQL dirs:
# /etc/postgresql/12/main/pg_hba.conf
# /usr/lib/postgresql/12/bin

- name: Set required configurations in sysctl.conf for PostgreSQL
  become: true
  become_user: root
  become_method: sudo
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { name: 'vm.max_map_count', value: '524288'}
    - { name: 'fs.file-max', value: '131072'}

- name: Increase ulimit and Update /etc/security/limits.conf for PostgreSQL
  become: true
  become_user: root
  become_method: sudo
  template:
    src: templates/limits.conf.j2
    dest: "{{ ulimit_config_location }}"
    # owner: root
    # group: root
    # mode: 0644

- name: Create PostgreSQL file repository configuration
  become: true
  become_method: sudo
  shell:
    cmd: sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'

- name: Import PostgreSQL repository signing key
  become: true
  become_method: sudo
  shell:
    cmd: wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -

# - name: Update APT packages
#   apt:
#     update_cache: yes
#     force_apt_get: yes
#     # upgrade: yes
#     # cache_valid_time: 86400 #One day

- name: Install PostgreSQL
  apt:
    name: postgresql-12
    state: present

- name: Ensure the PostgreSQL service is running
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Find out if PostgreSQL pg_hba.conf file exist
  stat:
    path: /etc/postgresql/12/main/pg_hba.conf
  register: postgres_data

- name: Allow trust connection for PostgreSQL local
  become: true
  become_method: sudo
  postgresql_pg_hba:
    dest: /etc/postgresql/12/main/pg_hba.conf
    contype: local
    databases: all
    method: trust
    users: all
    create: true
  when: postgres_data.stat.exists

- name: Allow md5 connection for PostgreSQL host
  become: true
  become_method: sudo
  postgresql_pg_hba:
    dest: /etc/postgresql/12/main/pg_hba.conf
    contype: host
    databases: all
    method: md5
    users: all
    create: true
  when: postgres_data.stat.exists

- name: Restart PostgreSQL service
  service:
    name: postgresql
    state: restarted

- name: Get PostgreSQL Version Info
  shell:
    cmd: sudo -u postgres /usr/lib/postgresql/12/bin/psql -c "SELECT version();"
  register: postgres_version_info

- name: Display PostgreSQL Version Info
  debug:
    var: postgres_version_info.stdout_lines

## After this, do below or follow manual steps: read files/manual-steps.txt

- name: Reset or set new password for postgres user in PostgreSQL
  become: true
  become_method: sudo
  user:
    name: postgres
    password: postgres
    update_password: always
    state: present

- name: Get current user info
  become: true
  become_method: sudo
  become_user: postgres
  shell:
    cmd: whoami
  register: whoami_info

- name: Print whoami info
  debug:
    var: whoami_info

- name: Copy PostgreSQL DB setup script for Sonarqube
  become: true
  become_method: sudo
  template:
    src: templates/sonarqubedb.sql.j2
    dest: /tmp/sonarqubedb.sql

- name: Setup PostgreSQL DB for sonarqube
  become: true
  become_user: postgres
  become_method: sudo
  shell:
    cmd: psql -f /tmp/sonarqubedb.sql
  register: db_setup_result

- name: Print PostgreSQL DB setup result
  debug:
    var: db_setup_result
