apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
data:
  #echo -n 'password'|base64
  #echo -n 'password'|sha256sum
  #echo -n 'password'|md5sum
  mariadb-root-password: 5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8  -