---
# tasks file for Gradle
- name: Update APT packages
  apt:
    # update_cache: yes
    # force_apt_get: yes
    # upgrade: yes
    # cache_valid_time: 86400 #One day
    state: latest

- name: Install Gradle package
  apt:
    pkg:
      - gradle
